//
// Created by Masayuki IZUMI on 2016/09/08.
//

#ifndef CIPOINTCLOUDVIEWERAPP_CLOUDDATASOURCESACTION_H
#define CIPOINTCLOUDVIEWERAPP_CLOUDDATASOURCESACTION_H

struct OpenPcdFilesDirectoryAction {
  std::string path;
};

#endif //CIPOINTCLOUDVIEWERAPP_CLOUDDATASOURCESACTION_H
